### ISSUE TITLE
兄台想请问下键鼠如何用gadget hid来实现，谢谢

### ISSUE THREAD

**Issue by leux0** [xzzpig/simple-ip-kvm#1]
谢谢大佬，已经在RK3588设备上跑起来了，HDMI输入用自带的HDMIRX。但现在不想用arduino来实现键盘鼠标，想通过系统自带的gadget hid来实现，该如何与simple-ip-kvm对接呢？
想请问下该如何使用

加了两个，一个键盘一个鼠标
root@iStoreOS:~# ls /dev/hidg
hidg0  hidg1
root@iStoreOS:~# ls /dev/video0
/dev/video0

**Comment by xzzpig** [comment]
目前是不支持gadget hid的，因为逻辑是照搬的open ip kvm，而且按后续计划是希望使用arduino模拟更多设备的。
如果是是arm设备的话可以看看能不能装[pi-kvm](https://pikvm.org/)，这个功能会更强大。
