### ISSUE TITLE
我应该配置什么文件

### ISSUE THREAD

**Issue by moyanjiang** [xzzpig/simple-ip-kvm#2]
我的安装了并且启动了但是一直是黑屏的，我不知道要配置和安装哪些东西

**Comment by xzzpig** [comment]
黑屏的话可以检查一下[ustreamer](https://github.com/pikvm/ustreamer)是否已经安装且运行正常。
配置文件可以参看示例文件 [assets/config-sample.yaml](https://github.com/xzzpig/simple-ip-kvm/blob/main/assets/config-sample.yaml)
