### ISSUE TITLE
能设置一个访问密码吗

### ISSUE THREAD

**Issue by hejunv** [xzzpig/simple-ip-kvm#3]
能设置一个访问密码吗，先验证密码再进入画面
[Nihiue/open-ip-kvm](https://github.com/Nihiue/open-ip-kvm) 之前这个打开ip+端口就能看见画面了，感觉很不安全特别是做了ddns，别人也能看到我的画面。

**Comment by xzzpig** [comment]
现在这版本就支持在配置文件中配置通过用户名密码登录验证(http basic auth)。
可以参考配置文件：
https://github.com/xzzpig/simple-ip-kvm/blob/1382a435812afe1ad474c85426350f22aa009db0/assets/config-sample.yaml#L12

**Comment by hejunv** [comment]
@xzzpig 大佬厉害，我之前是安装了caddy 用basic auth弄得。
